-- Création de la table Restaurants
CREATE TABLE Restaurants (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR2(255) NOT NULL,
    adresse VARCHAR2(255) NOT NULL,
    latitude NUMBER(10, 6) NOT NULL,
    longitude NUMBER(10, 6) NOT NULL
);

-- Insertion des données dans la table Restaurants
INSERT INTO Restaurants (nom, adresse, latitude, longitude) VALUES ('Le Bistrot', '12 Rue des Jardins, Nancy', 48.6921, 6.1844);
INSERT INTO Restaurants (nom, adresse, latitude, longitude) VALUES ('La Table Gourmande', '45 Avenue de la République, Nancy', 48.6953, 6.1812);
INSERT INTO Restaurants (nom, adresse, latitude, longitude) VALUES ('Le Petit Bistro', '78 Rue Saint-Dizier, Nancy', 48.6887, 6.1856);
INSERT INTO Restaurants (nom, adresse, latitude, longitude) VALUES ('Chez Marie', '33 Rue Saint-Michel, Nancy', 48.6876, 6.1821);
INSERT INTO Restaurants (nom, adresse, latitude, longitude) VALUES ('Le Gourmet', '56 Rue Saint-Jean, Nancy', 48.6901, 6.1834);

-- Création de la table Reservations
CREATE TABLE Reservations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id NUMBER NOT NULL,
    nom VARCHAR2(255) NOT NULL,
    prenom VARCHAR2(255) NOT NULL,
    nombre_convives NUMBER NOT NULL,
    telephone VARCHAR2(20) NOT NULL,
    dateres date NOT NULL,
    FOREIGN KEY (restaurant_id) REFERENCES Restaurants(id)
);

-- Insertion des données dans la table Reservations
INSERT INTO Reservations (restaurant_id, nom, prenom, nombre_convives, telephone, date_reservation) VALUES (1, 'Dupont', 'Jean', 4, '0612345678', TO_DATE('2025-06-10', 'YYYY-MM-DD'));
INSERT INTO Reservations (restaurant_id, nom, prenom, nombre_convives, telephone, date_reservation) VALUES (2, 'Martin', 'Sophie', 2, '0712345678', TO_DATE('2025-06-11', 'YYYY-MM-DD'));
INSERT INTO Reservations (restaurant_id, nom, prenom, nombre_convives, telephone, date_reservation) VALUES (3, 'Bernard', 'Luc', 6, '0687654321', TO_DATE('2025-06-12', 'YYYY-MM-DD'));
INSERT INTO Reservations (restaurant_id, nom, prenom, nombre_convives, telephone, date_reservation) VALUES (4, 'Petit', 'Emma', 3, '0798765432', TO_DATE('2025-06-13', 'YYYY-MM-DD'));
INSERT INTO Reservations (restaurant_id, nom, prenom, nombre_convives, telephone, date_reservation) VALUES (5, 'Moreau', 'Pierre', 5, '0654321876', TO_DATE('2025-06-14', 'YYYY-MM-DD'));


-- Création de la table Tables
CREATE TABLE Tables (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id NUMBER NOT NULL,
    numero_table NUMBER NOT NULL,
    capacite NUMBER NOT NULL,
    FOREIGN KEY (restaurant_id) REFERENCES Restaurants(id)
);

-- Insertion des données dans la table Tables
INSERT INTO Tables (restaurant_id, numero_table, capacite) VALUES (1, 1, 4);
INSERT INTO Tables (restaurant_id, numero_table, capacite) VALUES (1, 2, 6);
INSERT INTO Tables (restaurant_id, numero_table, capacite) VALUES (2, 1, 2);
INSERT INTO Tables (restaurant_id, numero_table, capacite) VALUES (2, 2, 4);
INSERT INTO Tables (restaurant_id, numero_table, capacite) VALUES (3, 1, 4);
INSERT INTO Tables (restaurant_id, numero_table, capacite) VALUES (3, 2, 8);
INSERT INTO Tables (restaurant_id, numero_table, capacite) VALUES (4, 1, 2);
INSERT INTO Tables (restaurant_id, numero_table, capacite) VALUES (4, 2, 4);
INSERT INTO Tables (restaurant_id, numero_table, capacite) VALUES (5, 1, 4);
INSERT INTO Tables (restaurant_id, numero_table, capacite) VALUES (5, 2, 6);

-- Création de la table de liaison ReservationTables
CREATE TABLE ReservationTables (
    reservation_id NUMBER NOT NULL,
    table_id NUMBER NOT NULL,
    PRIMARY KEY (reservation_id, table_id),
    FOREIGN KEY (reservation_id) REFERENCES Reservations(id),
    FOREIGN KEY (table_id) REFERENCES Tables(id)
);

-- Insertion des données dans la table ReservationTables
INSERT INTO ReservationTables (reservation_id, table_id) VALUES (1, 1);
INSERT INTO ReservationTables (reservation_id, table_id) VALUES (2, 3);
INSERT INTO ReservationTables (reservation_id, table_id) VALUES (3, 5);
INSERT INTO ReservationTables (reservation_id, table_id) VALUES (4, 7);
INSERT INTO ReservationTables (reservation_id, table_id) VALUES (5, 9);
